Repository oystparis/oyst-1click-magento, pull requests merged in 2018-03, with the labels that each got.

#296 Webshopapps Matrix rates fix (#294)
  app/code/community/Oyst/OneClick/Model/Catalog.php
Labels: quickfix

#298 Missing image for FreePay method (#152)
  app/code/community/Oyst/OneClick/Block/Form/Freepay.php
Labels: quickfix

#299 Configurable product price (#301)
  app/code/community/Oyst/OneClick/Model/Catalog.php
  app/code/community/Oyst/OneClick/Model/System/Config/Source/ConfigurablePrice.php
  app/code/community/Oyst/OneClick/etc/system.xml
  app/locale/en_US/Oyst_OneClick.csv
  app/locale/fr_FR/Oyst_OneClick.csv
Labels: enhancement

#302 Ignore shipping methods (#303)
  app/code/community/Oyst/OneClick/Block/Adminhtml/System/Config/Form/Fieldset/Carrier/Certified.php
  app/code/community/Oyst/OneClick/Block/Adminhtml/System/Config/Form/Fieldset/Carrier/Notcertified.php
  app/code/community/Oyst/OneClick/Helper/Shipments.php
  app/code/community/Oyst/OneClick/Model/Catalog.php
Labels: quickfix

#306 Fix informations info for configurable (#304)
  app/code/community/Oyst/OneClick/Model/Catalog.php
Labels: quickfix

#309 Create customer address (#308)
  app/code/community/Oyst/OneClick/Model/Magento/Quote.php
Labels: quickfix

#307 Fix for stock management on order creation (#305)
  README.md
  app/code/community/Oyst/OneClick/Model/Magento/Quote.php
  app/code/community/Oyst/OneClick/etc/config.xml
  var/connect/Oyst_OneClick.xml
Labels: quickfix

#313 Send new account email (#311)
  app/code/community/Oyst/OneClick/Model/Magento/Quote.php
Labels: feature

#312 Send new order mail (#310)
  app/code/community/Oyst/OneClick/Model/Order.php
Labels: feature

#261 OneClick checkout cart (#206)
  README.md
  app/code/community/Oyst/OneClick/Block/Checkout/Cart/Redirect.php
  app/code/community/Oyst/OneClick/Block/OneClick.php
  app/code/community/Oyst/OneClick/Helper/Data.php
  app/code/community/Oyst/OneClick/Model/Catalog.php
  app/code/community/Oyst/OneClick/Model/Magento/Quote.php
  app/code/community/Oyst/OneClick/Model/Observer.php
  app/code/community/Oyst/OneClick/Model/OneClick/ApiWrapper.php
  app/code/community/Oyst/OneClick/Model/Order.php
  app/code/community/Oyst/OneClick/Model/System/Config/Source/Catalog/Product/Button/Position.php
  app/code/community/Oyst/OneClick/Model/System/Config/Source/Checkout/Cart/Button/Position.php
  app/code/community/Oyst/OneClick/controllers/Checkout/CartController.php
  app/code/community/Oyst/OneClick/etc/config.xml
  app/code/community/Oyst/OneClick/etc/system.xml
  app/design/adminhtml/default/default/template/oyst/oneclick/notifications.phtml
  app/design/frontend/base/default/layout/oyst_oneclick.xml
  app/design/frontend/base/default/template/oyst/oneclick/checkout/cart/oneclick.phtml
  app/design/frontend/base/default/template/oyst/oneclick/checkout/cart/redirect.phtml
  app/locale/en_US/Oyst_OneClick.csv
  app/locale/fr_FR/Oyst_OneClick.csv
  skin/frontend/base/default/css/oyst/cart-redirect.css
  skin/frontend/base/default/js/oyst/checkout/cart/oneclick.js
  skin/frontend/base/default/js/oyst/checkout/cart/redirect.js
  var/connect/Oyst_OneClick.xml
Labels: feature
