Repository oystparis/oyst-1click-magento, pull requests merged in 2018-04, with the labels that each got.

#321 Disable product page button (#320)
  app/code/community/Oyst/OneClick/Block/OneClick.php
  app/code/community/Oyst/OneClick/Model/System/Config/Source/Catalog/Product/Button/Position.php
  app/code/community/Oyst/OneClick/etc/config.xml
  app/code/community/Oyst/OneClick/etc/system.xml
  app/code/community/Oyst/OneClick/sql/oyst_oneclick_setup/mysql4-upgrade-1.8.0-1.9.0.php
  app/design/frontend/base/default/template/oyst/oneclick/oneclick.phtml
Labels: enhancement

#333 Change theme button default value key to default (#332)
  app/code/community/Oyst/OneClick/Model/System/Config/Source/Button/Theme.php
  app/code/community/Oyst/OneClick/etc/config.xml
  app/code/community/Oyst/OneClick/etc/system.xml
  app/locale/en_US/Oyst_OneClick.csv
  app/locale/fr_FR/Oyst_OneClick.csv
Labels: enhancement

#316 Improve oneclick speed (#155)
  app/code/community/Oyst/OneClick/Model/Catalog.php
Labels: enhancement

#342 Change load logic of Oyst script.min.js (#341)
  README.md
  app/code/community/Oyst/OneClick/etc/config.xml
  app/design/frontend/base/default/layout/oyst_oneclick.xml
  app/design/frontend/base/default/template/oyst/oneclick/checkout/cart/oneclick.phtml
  app/design/frontend/base/default/template/oyst/oneclick/oneclick.phtml
  var/connect/Oyst_OneClick.xml
Labels: bug

#344 Fix shipment round (#343)
  README.md
  app/code/community/Oyst/OneClick/Model/Catalog.php
  app/code/community/Oyst/OneClick/etc/config.xml
  app/locale/fr_FR/Oyst_OneClick.csv
  var/connect/Oyst_OneClick.xml
Labels: quickfix
