Repository oystparis/oyst-1click-magento, pull requests merged in 2018-05, with the labels that each got.

#317 Generic Cart Rules (#292)
  app/code/community/Oyst/OneClick/Model/Catalog.php
  app/code/community/Oyst/OneClick/Model/Magento/Quote.php
  app/code/community/Oyst/OneClick/Model/OneClick/ApiWrapper.php
  app/code/community/Oyst/OneClick/etc/config.xml
  app/code/community/Oyst/OneClick/etc/system.xml
  app/locale/en_US/Oyst_OneClick.csv
  app/locale/fr_FR/Oyst_OneClick.csv
  var/connect/Oyst_OneClick.xml
Labels: feature

#318 Cart rules free items (#291)
  app/code/community/Oyst/OneClick/Model/Catalog.php
  app/code/community/Oyst/OneClick/etc/config.xml
  var/connect/Oyst_OneClick.xml
Labels: feature

#338 Order reference (#324)
  app/code/community/Oyst/OneClick/Model/Order.php
  app/code/community/Oyst/OneClick/Model/Order/ApiWrapper.php
Labels: feature

#348 Fix const dependency (#347)
  app/code/community/Oyst/OneClick/Model/Catalog.php
  var/connect/Oyst_OneClick.xml
Labels: bug

#355 Flush magento cart on order success (#352)
  app/code/community/Oyst/OneClick/Model/Magento/Order.php
  app/code/community/Oyst/OneClick/Model/Resource/Helper.php
Labels: bug

#349 Fix issue with cart promo subtotal rules that were not applied on Oyst popin (#328)
  app/code/community/Oyst/OneClick/Model/Magento/Quote.php
Labels: bug

#362 Fix pickup store shipment address (#356)
  README.md
  app/code/community/Oyst/OneClick/Model/Magento/Quote.php
  app/code/community/Oyst/OneClick/etc/config.xml
  var/connect/Oyst_OneClick.xml
Labels: bug

#353 Fix issue with only one shipment (#350)
  app/code/community/Oyst/OneClick/Model/Magento/Quote.php
  var/connect/Oyst_OneClick.xml
Labels: bug

#359 Refactoring checkout discount display on specifically for multiple discounts (#358)
  app/code/community/Oyst/OneClick/Model/Catalog.php
Labels: enhancement

#364 Configure oneclick with the IP restriction (#330)
  README.md
  app/code/community/Oyst/OneClick/Helper/Data.php
  app/code/community/Oyst/OneClick/Model/Observer.php
  app/code/community/Oyst/OneClick/etc/config.xml
  app/code/community/Oyst/OneClick/etc/system.xml
  app/design/frontend/base/default/layout/oyst_oneclick.xml
  app/locale/en_US/Oyst_OneClick.csv
  app/locale/fr_FR/Oyst_OneClick.csv
  var/connect/Oyst_OneClick.xml
Labels: feature

#368 Optimize shipmentTypes configuration load on system config (#367)
  app/code/community/Oyst/OneClick/Model/Catalog/ApiWrapper.php
  app/code/community/Oyst/OneClick/Model/System/Config/Source/ShipmentTypesList.php
Labels: enhancement

#371 Add last 4 credit card number into order payment information block (#273)
  app/code/community/Oyst/OneClick/Model/Magento/Quote.php
  app/code/community/Oyst/OneClick/Model/Observer.php
  app/code/community/Oyst/OneClick/etc/config.xml
Labels: feature

#375 Implement compliance for multi stock (#373)
  app/code/community/Oyst/OneClick/Model/Catalog.php
Labels: enhancement

#377 Add notifications status and manage zombies notifications (#346)
  app/code/community/Oyst/OneClick/Model/Catalog.php
  app/code/community/Oyst/OneClick/Model/Notification.php
  app/code/community/Oyst/OneClick/Model/Observer.php
  app/code/community/Oyst/OneClick/Model/Order.php
  app/code/community/Oyst/OneClick/Model/Payment/Data.php
  app/code/community/Oyst/OneClick/etc/config.xml
Labels: feature
